[package]
name = "text-generation-backends-trtllm"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
async-trait = "0.1.74"
async-stream = "0.3.5"
cxx = "1.0"
text-generation-router = { path = "../../router" }
tokio = { version = "1.32.0", features = ["rt", "rt-multi-thread", "parking_lot", "signal", "sync"] }
tokio-stream = "0.1.14"

[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"